DROP TABLE IF EXISTS ADVERTISEMENT;
CREATE TABLE ADVERTISEMENT (
AD_ID LONG PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(255),
CONTEXT VARCHAR(255),
IMAGE_URL VARCHAR(255),
LANGUAGE VARCHAR(255),
);

DROP TABLE IF EXISTS DEVICES;
CREATE TABLE DEVICES (
  DEV_ID LONG PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255),
  MODEL VARCHAR(255),
  DEVICE_TYPE VARCHAR(255)
);

DROP TABLE IF EXISTS PROVIDER;
CREATE TABLE PROVIDER (
  PROV_ID LONG PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255),
  ADDRESS VARCHAR(255),
  TELEPHONE VARCHAR(255),
  COUNTRY VARCHAR(255)
);

DROP TABLE IF EXISTS PUBLISHER;
CREATE TABLE PUBLISHER (
  PUB_ID LONG PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255),
  ADDRESS VARCHAR(255),
  TELEPHONE VARCHAR(255),
  COUNTRY VARCHAR(255)
);