CREATE TABLE IF NOT EXISTS ORDERS(
          ID INT AUTO_INCREMENT PRIMARY KEY,
          NUMBER INT,
          PRICE DOUBLE,
          DELIVERY_INCLUDED BOOLEAN,
          DELIVERY_COST INT,
          EXECUTED BOOLEAN);