CREATE TABLE IF NOT EXISTS USERS(
  USER_ID INT AUTO_INCREMENT PRIMARY KEY,
  PHONE_NUMBER VARCHAR(35),
  NAME VARCHAR(250),
  SECOND_NAME VARCHAR(250),
  COUNTRY VARCHAR(250),
  EMAIL_ADDRESS VARCHAR(250));