--AIRPORT
INSERT INTO AIRPORT (APNAME, APNUM, APTYPE, ADDRESS, TERMINALCOUNT) VALUES ('Kenedy','12345','international','New York',10);
INSERT INTO AIRPORT (APNAME, APNUM, APTYPE, ADDRESS, TERMINALCOUNT) VALUES ('Changy','54367','international','Singapur',15);
INSERT INTO AIRPORT (APNAME, APNUM, APTYPE, ADDRESS, TERMINALCOUNT) VALUES ('Shiphol','32456','international','Shanhai',11);
INSERT INTO AIRPORT (APNAME, APNUM, APTYPE, ADDRESS, TERMINALCOUNT) VALUES ('Dallas/fort-uert','86345','international','Dallas',10);
INSERT INTO AIRPORT (APNAME, APNUM, APTYPE, ADDRESS, TERMINALCOUNT) VALUES ('Sharl-de-goll','14562','international','Paris',8);
INSERT INTO AIRPORT (APNAME, APNUM, APTYPE, ADDRESS, TERMINALCOUNT) VALUES ('Hitrou','32674','international','London',9);
INSERT INTO AIRPORT (APNAME, APNUM, APTYPE, ADDRESS, TERMINALCOUNT) VALUES ('O-hara','83257','international','Chicago',7);